<a href="https://colab.research.google.com/github/patel-star/Data-Scienceeee/blob/main/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[2,3,5],[4,5,6]], dtype='int64')
b= np.array([2.0,2.2,3.4])
print(a)

[[2 3 5]
 [4 5 6]]


In [ ]:
#get dimension
a.ndim

2

In [ ]:
#get shape
a.shape

(2, 3)

In [ ]:
#type
a.dtype
b.dtype

dtype('float64')

In [ ]:
# get size
a.itemsize
b.itemsize

8

In [ ]:
#get total size (no. of elements)
a.size
b.size

3

In [ ]:
#total size: a.size * a.itemsize same as:
a.nbytes
b.nbytes

24

# Accesing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
#get specific element [row, column]
a[0, 5]

np.int64(6)

In [ ]:
# get a specific row:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#get a specific column:
a[: ,2]

array([ 3, 10])

In [ ]:
# getting a little more fancy [startindex: endindex: stepsize]
print(a)

a[1, 1:6:2]
# a[0, 1:-1:2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([ 9, 11, 13])

In [ ]:
#replace a element:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [ ]:
#replace specific row,or columns:
a[:, 2]= [1,2]
print(a)

a[:, 3]=5
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  5  5  6  7]
 [ 8  9  2  5 12 20 14]]


# 3D examples:

In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# get a specific element:
# b[0,1,1] ---4
b[1,0,1]

np.int64(6)

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [ ]:
#replace in 3d:
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# initializing Different types of array:

In [ ]:
# All 0s matrix creation:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Alll 1s matrix:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
# Any other number:
np.full((2,3),88,dtype='float32')

array([[88., 88., 88.],
       [88., 88., 88.]], dtype=float32)

In [ ]:
# Any other number (full_like):
print(a)
np.full(a.shape,5)

[[ 1  2  1  5  5  6  7]
 [ 8  9  2  5 12 20 14]]


array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [ ]:
# random decimal number and matrix:
np.random.rand(4,2)

array([[0.17591971, 0.07217745],
       [0.56830226, 0.89100908],
       [0.96412424, 0.44886846],
       [0.95208458, 0.87603266]])

In [ ]:
# same shape as a and random numbers replacing it:
np.random.random_sample(a.shape)

array([[0.62484425, 0.43020068, 0.32944209, 0.02349335, 0.27916335,
        0.03888799, 0.52841731],
       [0.80287816, 0.00631198, 0.2789001 , 0.0980469 , 0.26798065,
        0.82622573, 0.17837221]])

In [ ]:
#random integer value:
np.random.randint(90,size=(3,3)) #from 0-89
np.random.randint(-4,8,size=(3,3)) #from -4 to 7

array([[-3,  1,  7],
       [-3, -1,  5],
       [-3, -3,  6]])

In [ ]:
# the identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# repeat array multiple times:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Question solution:
import numpy as np
arr1=np.ones((5,5))
arr1[:-1,:-1]=0
arr1[:,0]=1
arr1[0,:]=1
arr1[2,2]=9
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#solution 2:
up=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
up[1:4,1:4] = z #up[1:-1,1:-1]
up

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying!!!

In [ ]:
# example
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [ ]:
# solutiion
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# **Mathematics**:

In [ ]:
a=np.array([1,2,3,4])
print(a)
print(a+2)
a/2
a **2

[1 2 3 4]
[3 4 5 6]


array([ 1,  4,  9, 16])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# **Linear Algebra**

In [ ]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
# matrix multiplication:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinant of matrix
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
# Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# ***Statistics:***

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

np.int64(1)

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# ***Reorganizing arrays:***

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
after = np.reshape(before,(8,1))
print(after)

before.reshape((4,2)) #must be same no of elements it can be 2,2,2

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#Vertically stacking vectors:
v1= np.array([1,3,4,5])
v2= np.array([6,7,8,9])
np.vstack([v1,v1,v2])

array([[1, 3, 4, 5],
       [1, 3, 4, 5],
       [6, 7, 8, 9]])

In [ ]:
# Horizontal stack:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h2,h1,h2))

array([[0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.]])

# **Miscellaneous**
### *Load Data from file*

In [ ]:
data = np.genfromtxt('data.txt', delimiter=',')
data.astype('int32') #temporary copy

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [ ]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

## *Boolean masking and advanced indexing*

In [ ]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
data[data>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [ ]:
np.any(data>=55, axis=0) # or any --> all

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(data>50, axis=1)

array([False, False, False])

In [ ]:
(~((data < 100) & (data > 50)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
# you can index with list inn numpy
a = np.array([1,3,4,5,6,7,7,8,9])
a[[1,3,8]]

array([3, 5, 9])

In [ ]:
# Question:
matrix = np.arange(1, 31).reshape(6, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Q.1 access 11 , 12 16 17
matrix[2:4,0:2]

#Q.2 access : 2,8,14,20
matrix[[0,1,2,3],[1,2,3,4]]

array([[11, 12],
       [16, 17]])

In [ ]:
# Q.3 access 4,5,24,25,29 30
matrix[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])