In [32]:
import numpy as np
import pandas as pd
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
42   30  Female     Good        PG       Yes
6    18    Male     Good    School        No
32   92    Male  Average        UG       Yes
22   18  Female     Poor        PG       Yes
2    70  Female     Good        PG        No

In [33]:
df = df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df.purchased,random_state=0,test_size=0.3)
x_train.shape 
y_test

28     No
11    Yes
10    Yes
41    Yes
2      No
27     No
38     No
31    Yes
22    Yes
4      No
33    Yes
35    Yes
26     No
34     No
18     No
Name: purchased, dtype: object

In [36]:
# ordinal encoder encodes based on the weight or importance of categories. ex-good is more and poor is less important,weight
from sklearn.preprocessing import OrdinalEncoder
x_train

review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [37]:
# this encoding is given in order so it prioritize the good then avg and then poor, if not assigned then it will select randomly
oe = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])

In [38]:
# now to train:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [39]:
# now its trained lets encode all:
x_train = oe.transform(x_train)
x_train
# we can compare it to previous x_train poor-0,school-0: 1st row

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [40]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [41]:
x_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [42]:
# now till now it was ordinal encoder now lets see label encoder:
# label encoder is for yes no,off on,etc have same weight unlike ordinal
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train

7     Yes
14    Yes
45    Yes
48    Yes
29    Yes
15     No
30     No
32    Yes
16    Yes
42    Yes
20    Yes
43     No
8      No
13     No
25     No
5     Yes
17    Yes
40     No
49     No
1      No
12     No
37    Yes
24    Yes
6      No
23     No
36    Yes
21     No
19    Yes
9     Yes
39     No
46     No
3      No
0      No
47    Yes
44     No
Name: purchased, dtype: object

In [46]:
le.fit(y_train)


LabelEncoder()

In [44]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [45]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])